### ISSUE TITLE
 Checkout process

### ISSUE THREAD

**Issue by tedstriker** [Ardobras/lieferheld-api#1]
Hi there,
Do you still plan implementing the checkout ability?
Regards
Ted

**Comment by kenodressel** [comment]
We are not. But we would love if you would try it and create a pull request.

Am 19.02.2018 01:37 schrieb "tedstriker" <notifications@github.com>:

**Comment by tedstriker** [comment]
I think I lack the ability to do so, but I'm glad you're willing to merge other contributors improvements. Thank you.
